### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by tmytro** [idealo/terraform-provider-controltower#16]
Please add package for ARM processors, currently I'm getting the following error message:
 
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/idealo/controltower v1.0.3 does not have a package available for your current platform, darwin_arm64.

**Comment by mbrettschneider** [comment]
Hi tmytro,
are you able to create a pull request with the needed changes yourself?

**Comment by mKeRix** [comment]
Macs with ARM64 processors should be supported by the latest release, v1.0.4.
