### ISSUE TITLE
Support for Assume_Role block

### ISSUE THREAD

**Issue by elabbarw** [idealo/terraform-provider-controltower#17]
Can you add support for the assume_role block under the provider please?

Thanks!

**Comment by elabbarw** [comment]
Working on it myself

**Comment by elabbarw** [comment]
Hello,

Can someone review my pull request please? Thanks!

https://github.com/idealo/terraform-provider-controltower/pull/19

**Comment by mKeRix** [comment]
Reviewed it - already had it on my list since this morning, but my day is quite busy so I only got to it now.

**Comment by mKeRix** [comment]
This is now live in v1.1.0. I also took the liberty to add the other settings, so that the controltower provider should match the official AWS one now.
