### ISSUE TITLE
controltower_aws_account.account: Creating...  Error: unexpected number of search results: 0    on controltower.tf line 16, in resource "controltower_aws_account" "account":   16: resource "controltower_aws_account" "account" {

### ISSUE THREAD

**Issue by crlmas** [idealo/terraform-provider-controltower#22]
created a new aws account, passed that email as root account email in resource. For autentication, have passed access and secret key in provider (have created a iam user with admin and service catalog admin access ). when running terraform apply it is giving me error rror: unexpected number of search results: 0

on controltower.tf line 16, in resource "controltower_aws_account" "account":
16: resource "controltower_aws_account" "account" {

I am not sure where it is going wrong, also not passing any product id

**Comment by crlmas** [comment]
created a new aws account, passed that email as root account email in resource. For autentication, have passed access and secret key in provider (have created a iam user with admin and service catalog admin access ). when running terraform apply it is giving me error rror: unexpected number of search results: 0

  on controltower.tf line 16, in resource "controltower_aws_account" "account":
  16: resource "controltower_aws_account" "account" {

I am not sure where it is going wrong, also not passing any product id

**Comment by mKeRix** [comment]
Check issue #7 - you need to share the service catalog portfolio with your IAM user to use it.
