### ISSUE TITLE
Search products returning no results

### ISSUE THREAD

**Issue by kchowdhree** [idealo/terraform-provider-controltower#7]
Hi,

Been attempting to use this provider to provision an AWS account via Control Tower's account factory, but it returns "Error: unexpected number of search results: 0" , here's the trace log output from TF - any ideas of the issue?

2021/06/13 15:10:52 [TRACE] eval: terraform.EvalNoop
2021/06/13 15:10:52 [TRACE] [walkApply] Exiting eval tree: provider["registry.terraform.io/idealo/controltower"]
2021/06/13 15:10:52 [TRACE] vertex "provider[\"registry.terraform.io/idealo/controltower\"]": visit complete
2021/06/13 15:10:52 [TRACE] dag/walk: visiting "controltower_aws_account.account (expand)"
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account (expand)": starting visit (*terraform.nodeExpandApplyableResource)
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account (expand)": expanding dynamic subgraph
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account (expand)": entering dynamic subgraph
2021/06/13 15:10:52 [TRACE] dag/walk: visiting "controltower_aws_account.account"
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account": starting visit (*terraform.NodeApplyableResource)
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account": evaluating
2021/06/13 15:10:52 [TRACE] [walkApply] Entering eval tree: controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalWriteResourceState
2021/06/13 15:10:52 [TRACE] [walkApply] Exiting eval tree: controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account": visit complete
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account (expand)": dynamic subgraph completed successfully
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account (expand)": visit complete
2021/06/13 15:10:52 [TRACE] dag/walk: visiting "controltower_aws_account.account"
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account": starting visit (*terraform.NodeApplyableResourceInstance)
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account": evaluating
2021/06/13 15:10:52 [TRACE] [walkApply] Entering eval tree: controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalSequence
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalGetProvider
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalReadDiff
2021/06/13 15:10:52 [TRACE] EvalReadDiff: Read Create change from plan for controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalIf
2021/06/13 15:10:52 [TRACE] eval: terraform.EvalNoop
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalIf
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalReadState
2021/06/13 15:10:52 [TRACE] EvalReadState: reading state for controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] EvalReadState: no state present for controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalReadDiff
2021/06/13 15:10:52 [TRACE] EvalReadDiff: Read Create change from plan for controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalDiff
2021/06/13 15:10:52 [TRACE] Re-validating config for "controltower_aws_account.account"
2021/06/13 15:10:52 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2021/06/13 15:10:52 [TRACE] GRPCProvider: PlanResourceChange
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalCheckPlannedChange
2021/06/13 15:10:52 [TRACE] EvalCheckPlannedChange: Verifying that actual change (action Create) matches planned change (action Create)
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalGetProvider
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalReadState
2021/06/13 15:10:52 [TRACE] EvalReadState: reading state for controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] EvalReadState: no state present for controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalReduceDiff
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalIf
2021/06/13 15:10:52 [TRACE] eval: terraform.EvalNoop
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalApplyPre
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalApply
2021/06/13 15:10:52 [DEBUG] EvalApply: ProviderMeta config value set
2021/06/13 15:10:52 [DEBUG] controltower_aws_account.account: applying the planned Create change
2021/06/13 15:10:52 [TRACE] GRPCProvider: ApplyResourceChange
controltower_aws_account.account: Creating...
2021-06-13T15:10:52.237Z [INFO]  plugin.terraform-provider-controltower_v1.0.2: 2021/06/13 15:10:52 [DEBUG] [aws-sdk-go] DEBUG: Request servicecatalog/SearchProducts Details:
---[ REQUEST POST-SIGN ]-----------------------------
POST / HTTP/1.1
Host: servicecatalog.us-east-1.amazonaws.com
User-Agent: APN/1.0 HashiCorp/1.0 Terraform/0.13.0 (+https://www.terraform.io) terraform-provider-controltower/1.0.2 (+https://registry.terraform.io/providers/idealo/controltower) aws-sdk-go/1.38.44 (go1.14.15; linux; amd64) TFC/973475467c
Content-Length: 68
Authorization: AWS4-HMAC-SHA256 Credential=XXXXREDACTEDXXXX/20210613/us-east-1/servicecatalog/aws4_request, SignedHeaders=content-length;content-type;host;x-amz-date;x-amz-target, Signature=XXXXREDACTEDXXXX
Content-Type: application/x-amz-json-1.1
X-Amz-Date: 20210613T151052Z
X-Amz-Target: AWS242ServiceCatalogService.SearchProducts
Accept-Encoding: gzip

{"Filters":{"FullTextSearch":["AWS Control Tower Account Factory"]}}
-----------------------------------------------------: timestamp=2021-06-13T15:10:52.237Z
2021-06-13T15:10:52.311Z [INFO]  plugin.terraform-provider-controltower_v1.0.2: 2021/06/13 15:10:52 [DEBUG] [aws-sdk-go] DEBUG: Response servicecatalog/SearchProducts Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 95
Content-Type: application/x-amz-json-1.1
Date: Sun, 13 Jun 2021 15:10:51 GMT
X-Amzn-Requestid: d4aff6f2-ad03-47c5-XXXXREDACTEDXXXX

-----------------------------------------------------: timestamp=2021-06-13T15:10:52.311Z
2021-06-13T15:10:52.311Z [INFO]  plugin.terraform-provider-controltower_v1.0.2: 2021/06/13 15:10:52 [DEBUG] [aws-sdk-go] {"ProductViewAggregations":{"Owner":[],"ProductType":[],"Vendor":[]},"ProductViewSummaries":[]}: timestamp=2021-06-13T15:10:52.311Z
2021/06/13 15:10:52 [DEBUG] controltower_aws_account.account: apply errored, but we're indicating that via the Error pointer rather than returning it: unexpected number of search results: 0
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalMaybeTainted
2021/06/13 15:10:52 [TRACE] EvalMaybeTainted: controltower_aws_account.account encountered an error during creation, so it is now marked as tainted
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalWriteState
2021/06/13 15:10:52 [TRACE] EvalWriteState: removing state object for controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalApplyProvisioners
2021/06/13 15:10:52 [TRACE] EvalApplyProvisioners: controltower_aws_account.account has no state, so skipping provisioners
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalMaybeTainted
2021/06/13 15:10:52 [TRACE] EvalMaybeTainted: controltower_aws_account.account encountered an error during creation, so it is now marked as tainted
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalWriteState
2021/06/13 15:10:52 [TRACE] EvalWriteState: removing state object for controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalIf
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalIf
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalWriteDiff
2021/06/13 15:10:52 [TRACE] eval: *terraform.EvalApplyPost
2021/06/13 15:10:52 [ERROR] eval: *terraform.EvalApplyPost, err: unexpected number of search results: 0
2021/06/13 15:10:52 [ERROR] eval: *terraform.EvalSequence, err: unexpected number of search results: 0
2021/06/13 15:10:52 [TRACE] [walkApply] Exiting eval tree: controltower_aws_account.account
2021/06/13 15:10:52 [TRACE] vertex "controltower_aws_account.account": visit complete
2021/06/13 15:10:52 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/idealo/controltower\"] (close)" errored, so skipping
2021/06/13 15:10:52 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2021/06/13 15:10:52 [TRACE] dag/walk: upstream of "root" errored, so skipping

Error: unexpected number of search results: 0

  on main.tf line 35, in resource "controltower_aws_account" "account":
  35: resource "controltower_aws_account" "account" {

2021-06-13T15:10:52.314Z [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-06-13T15:10:52.315Z [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/idealo/controltower/1.0.2/linux_amd64/terraform-provider-controltower_v1.0.2 pid=1552
2021-06-13T15:10:52.315Z [DEBUG] plugin: plugin exited

**Comment by mKeRix** [comment]
Are you executing Terraform under an extra user or role? Or are you using your own SSO admin credentials? If so: The account factory service catalog is assigned only to some permission sets by default, others won't be able to see the product. You can assign it to more roles and users either in the management console web UI, or via Terraform like so:

```terraform
resource "aws_servicecatalog_principal_portfolio_association" "account_manager_account_factory" {
  portfolio_id  = var.account_factory_portfolio_id
  principal_arn = aws_iam_role.account_manager.arn
}
```

**Comment by kchowdhree** [comment]
I was running it as admin in the root control tower account with full rights, i.e. I can see the account factory product under service catalog in the AWS ui..is there anything else I can look into to debug?

**Comment by mKeRix** [comment]
Do you see it under the regular "Products" tab as well? There's two of them that are different, one is regular and the other one is under "Administration". It needs to be visible under Regular. That threw me for a loop a while ago at least.

Apart from that, you can replicate this call by running `aws servicecatalog search-products --filters "FullTextSearch=AWS Control Tower Account Factory"` with the same credentials (although that will likely results in the same output as your debug log). Maybe also double check that the name of the product matches the search query, if not that would be a bug.

**Comment by kchowdhree** [comment]
The AWS servicecatalog command returns no results too (and the name does match the search string) but per your comment it is under the "Admininstration -> Products" section - how do I make it visible under the "regular" menu? (alhough It does already show under the "Products" link too that i've circled on the screenshot:
![image](https://user-images.githubusercontent.com/63188522/121904528-2c8d3a80-cd21-11eb-9787-c3bcfd84dd75.png))

**Comment by mKeRix** [comment]
The Products menu that you circled is the relevant one already actually, so you should be good on that front. Essentially, the account factory service catalog portfolio needs to be shared with whatever identity Terraform uses to do its API calls (you can check with `aws sts get-caller-identity`). You can do this in Terraform like mentioned above or in the web UI with the marked button:

![Bildschirmfoto 2021-06-14 um 18 59 35](https://user-images.githubusercontent.com/770596/121930648-e77a0000-cd42-11eb-8e8b-7daf83710f50.png)

**Comment by kchowdhree** [comment]
Adding the user into that screen moved me along, thanks, but now I get this error:

Terraform v1.0.0
on linux_amd64
Configuring remote state backend...
Initializing Terraform configuration...
controltower_aws_account.account: Refreshing state... [id=pp-wXXXREDACTEDXXX]
╷
│ Error: could not find account ID in provisioned product
│ 
│   with controltower_aws_account.account,
│   on main.tf line 24, in resource "controltower_aws_account" "account":
│   24: resource "controltower_aws_account" "account" {
│ 
╵


**Comment by mKeRix** [comment]
Two questions to that:

- Are you using the latest provider version (1.0.2)?
- What is the state of your provisioned product? Does it have at least one successful provisioning record with an `AccountId` output key attached?

**Comment by kchowdhree** [comment]
- Yes tried with 1.0.2 as well
- Yes if you mean have I provisioned any accounts via the CT UI? I have accounts in there with accountids.

**Comment by mKeRix** [comment]
You can replicate these API calls as well to see what's going on:

```shell
aws servicecatalog describe-provisioned-product --id <id-of-your-provisioned-product>
aws servicecatalog describe-record --id <LastSuccessfulProvisioningRecordId or LastProvisioningRecordId from previous output>
```

The described record should contain the AccountId output key. It would also be interesting to know the type and status of the record that is being read.

**Comment by kchowdhree** [comment]
OK it's working now! 

It was a combo of missing permissions and conflicting remote state file.

So are you actively using this provider in production, and planning further enhancements and/or more control tower hooks?

**Comment by mKeRix** [comment]
Glad to hear that! I'll close this issue then.

We are indeed actively using this in production and will therefore at the very least maintain this provider with security updates etc. Unfortunately, the APIs around Control Tower are still quite scarce (many things can only be done in the web UI), but I could imagine that we add more things if they are opened up in an API. We're also open for feature request issues and/or pull request contributions.

**Comment by kchowdhree** [comment]
Sorry need to re-open as I think the issues I had above may be a bug. 

i'm using Terraform Cloud as the backend, if an account provisioning fails for any reason (e.g. non-unique accountname when I try to create a new account), I get those "could not find account ID" errors again.

The only solution is to delete my backend statefile (i.e. TFC workspace) to reset state.

For example, using random accountnames, the first one failed as the name was too long, I tried again and get this error:

random_pet.rnd: Refreshing state... [id=heavily-briefly-precious-gazelle]
controltower_aws_account.account: Refreshing state... [id=pp-XXXXXXXXXXX]
╷
│ Error: could not find account ID in provisioned product
│
│   with controltower_aws_account.account,
│   on main.tf line 5, in resource "controltower_aws_account" "account":
│    5: resource "controltower_aws_account" "account" {
│

The only way to continue create accounts is to destroy my backend workspace, create a new one/init and then run my TF account creation again.

**Comment by mKeRix** [comment]
I opened a new issue for this, since it's not really related to the original post anymore: #9

**Comment by crlmas** [comment]
I have given this permission "
AWS managed policy

 AWSServiceCatalogAdminFullAccess" via console to the iam user which
